### ISSUE TITLE
Fix example configuration in README.md

### ISSUE THREAD

**Issue by mark-strasser-nnl** [GunnarFarneback/LocalPackageServer.jl#11]
The example configuration file (`host` param) in `README.md` is incorrect and causes the server to abort on startup.

https://github.com/GunnarFarneback/LocalPackageServer.jl/blob/d1b752483a1d31b757c5237339d27ce1a9c8be6f/README.md?plain=1#L34

### Behavior

Aborts with error on startup.

### Expected behavior

Server should start normally with the example configuration.

### Error message

> julia --project bin/run_server.jl ../localpackageserver-configs/config.toml
> ┌ Info: server listening on localhost:8000
> └   Dates.now() = 2024-05-10T17:09:50.356
> ERROR: LoadError: ArgumentError: invalid base 10 digit 'l' in "localhost"

### Suggested fix

Update the example in `README.md` to state `host = "127.0.0.1"`.

**Comment by GunnarFarneback** [comment]
Thanks for the report. Fixed in #12.
